# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 01:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_auto_20160614_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 6, 20, 1, 12, 35, 933919, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 6, 19)),
        ),
    ]
