# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 22:30
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0004_auto_20160619_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 6, 21)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='pubyr',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1900), django.core.validators.MinValueValidator(2016)]),
        ),
    ]
