# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 22:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0005_auto_20160621_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='pubyr',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2016), django.core.validators.MinValueValidator(1900)]),
        ),
    ]
