# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0006_auto_20160621_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='libuser',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
