# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0007_libuser_model_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libuser',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='libapp/static/pic_folder/'),
        ),
    ]
